# -*- coding: utf-8 -*-
"""Analise_Quod.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFX2qYQytAesVF9zIltOyiaglx9FQ-rc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Lendo dataset
dadosvendas= pd.read_csv("data_clean_comtotaldevendas.csv")

dadosvendas.head(10)

#tratando a coluna data
dadosvendas['Data'] = pd.to_datetime(dadosvendas['Data'])

#criando uma coluna de mês/ano para agrupar as datas
dadosvendas['MesAno'] = dadosvendas['Data'].dt.to_period('M')

#fazendo o total de vendas por mes
vendaspormes = dadosvendas.groupby('MesAno')['Total de Vendas'].sum()

#criando o gráfico de linha
plt.figure(figsize=(15,8))
plt.plot(vendaspormes.index.astype(str), vendaspormes.values, marker='o', color='skyblue')
plt.title('Tendencia de Vendas Mensais')
plt.xlabel('Mês')
plt.ylabel('Total De Vendas')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

#criando grafico de barras de valor dos produtos por mes

dadosvendas_agrupado = dadosvendas.groupby(['MesAno', 'Produto'])['Quantidade'].sum().unstack(fill_value=0)
dadosvendas_agrupado.plot(kind='bar', figsize=(12,6))
plt.title('Vendas Mensais por Produto')
plt.xlabel('Mês/Ano')
plt.ylabel('Quantidade Vendida')
plt.xticks(rotation=45)
plt.legend(title="Produto", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

#agrupar a quantidade de produtos vendidos
vendas_produto = dadosvendas.groupby('Produto')['Quantidade'].sum().sort_values(ascending=False)

# gráfico de barras de quantidade de produtos mais vendidos no decorrer do ano
plt.figure(figsize=(15,6))
vendas_produto.plot(kind='bar', color='skyblue')
plt.title('Quantidade de Produtos Vendidos')
plt.xlabel('Produto')
plt.ylabel('Quantidade Vendida')
plt.xticks(rotation=90)
plt.show()

#agrupar a quantidade de produtos vendidos
vendas_produtos = dadosvendas.groupby('Produto')['Total de Vendas'].sum().sort_values(ascending=True)
plt.figure(figsize=(15,6))
vendas_produtos.plot(kind='barh', color='skyblue')
plt.title('Total de Vendas por Produto')
plt.xlabel('Valor Total Vendido')
plt.show()